### ISSUE TITLE
Python 3.8 failures

### ISSUE THREAD

**Issue by hroncok** [serge-sans-paille/gast#33]
In Fedora, we try to rebuild packages with Python 3.8.0b1. This is gast 0.2.2:

```
/usr/bin/python3 setup.py test
testCompile (tests.test_self.SelfTestCase) ... ERROR
testParse (tests.test_self.SelfTestCase) ... ok
test_unparse (tests.test_self.SelfTestCase) ... ERROR
test_NodeTransformer (tests.test_api.APITestCase) ... ok
test_NodeVisitor (tests.test_api.APITestCase) ... ok
test_copy_location (tests.test_api.APITestCase) ... ok
test_dump (tests.test_api.APITestCase) ... ok
test_fix_missing_locations (tests.test_api.APITestCase) ... ok
test_get_docstring (tests.test_api.APITestCase) ... FAIL
test_increment_lineno (tests.test_api.APITestCase) ... ok
test_iter_child_nodes (tests.test_api.APITestCase) ... ok
test_iter_fields (tests.test_api.APITestCase) ... ok
test_literal_eval_code (tests.test_api.APITestCase) ... ok
test_literal_eval_string (tests.test_api.APITestCase) ... ok
test_parse (tests.test_api.APITestCase) ... ok
test_walk (tests.test_api.APITestCase) ... FAIL
test_ArgAnnotation (tests.test_compat.CompatTestCase) ... ERROR
test_Call (tests.test_compat.CompatTestCase) ... ERROR
test_FormattedValue (tests.test_compat.CompatTestCase) ... ERROR
test_JoinedStr (tests.test_compat.CompatTestCase) ... ERROR
test_KeywordOnlyArgument (tests.test_compat.CompatTestCase) ... ERROR
test_TryExceptNamed (tests.test_compat.CompatTestCase) ... ERROR

======================================================================
ERROR: testCompile (tests.test_self.SelfTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_self.py", line 27, in testCompile
    compile(gast.gast_to_ast(gnode), src_py, 'exec')
TypeError: arguments field "posonlyargs" must be a list, not a NoneType

======================================================================
ERROR: test_unparse (tests.test_self.SelfTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_self.py", line 34, in test_unparse
    astunparse.unparse(gast.gast_to_ast(gnode))
  File "/usr/lib/python3.8/site-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 78, in _Module
    self.dispatch(stmt)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 328, in _ClassDef
    self.dispatch(t.body)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 63, in dispatch
    self.dispatch(t)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 347, in _FunctionDef
    self._generic_FunctionDef(t)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 337, in _generic_FunctionDef
    self.dispatch(t.args)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/lib/python3.8/site-packages/astunparse/unparser.py", line 763, in _arguments
    defaults = [None] * (len(t.args) - len(t.defaults)) + t.defaults
AttributeError: 'arguments' object has no attribute 'defaults'

======================================================================
ERROR: test_ArgAnnotation (tests.test_compat.CompatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_compat.py", line 48, in test_ArgAnnotation
    compile(gast.gast_to_ast(tree), '<test>', 'exec')
TypeError: arguments field "posonlyargs" must be a list, not a NoneType

======================================================================
ERROR: test_Call (tests.test_compat.CompatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_compat.py", line 63, in test_Call
    compile(gast.gast_to_ast(tree), '<test>', 'exec')
ValueError: field value is required for keyword

======================================================================
ERROR: test_FormattedValue (tests.test_compat.CompatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_compat.py", line 70, in test_FormattedValue
    compile(gast.gast_to_ast(tree), '<test>', 'exec')
ValueError: field value is required for Assign

======================================================================
ERROR: test_JoinedStr (tests.test_compat.CompatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_compat.py", line 75, in test_JoinedStr
    compile(gast.gast_to_ast(tree), '<test>', 'exec')
ValueError: field value is required for Assign

======================================================================
ERROR: test_KeywordOnlyArgument (tests.test_compat.CompatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_compat.py", line 53, in test_KeywordOnlyArgument
    compile(gast.gast_to_ast(tree), '<test>', 'exec')
TypeError: arguments field "posonlyargs" must be a list, not a NoneType

======================================================================
ERROR: test_TryExceptNamed (tests.test_compat.CompatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_compat.py", line 58, in test_TryExceptNamed
    compile(gast.gast_to_ast(tree), '<test>', 'exec')
TypeError: required field "type_ignores" missing from Module

======================================================================
FAIL: test_get_docstring (tests.test_api.APITestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_api.py", line 69, in test_get_docstring
    self.assertEqual(docs, "foo")
AssertionError: None != 'foo'

======================================================================
FAIL: test_walk (tests.test_api.APITestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/gast-0.2.2/tests/test_api.py", line 45, in test_walk
    self.assertEqual(dump, norm)
AssertionError: "Expr[30 chars]='x', ctx=Load(), annotation=None), op=Add(), right=None))" != "Expr[30 chars]='x', ctx=Load(), annotation=None), op=Add(), right=Num(n=1)))"
- Expression(body=BinOp(left=Name(id='x', ctx=Load(), annotation=None), op=Add(), right=None))
?                                                                                        ^ ^
+ Expression(body=BinOp(left=Name(id='x', ctx=Load(), annotation=None), op=Add(), right=Num(n=1)))
?                                                                                        ^^^ ^^^


----------------------------------------------------------------------
Ran 22 tests in 0.069s

FAILED (failures=2, errors=8)
```

**Comment by serge-sans-paille** [comment]
@hroncok : #27 fixes the issue, but beware, it's incompatible with current pythran version. This is fixed at conda and pypi level by forcing a version in the requirements, for fedora it's probably better to wait pythran (and beniget) upgrade. I'm going to upgrade beniget soon and I have all tests passing for pythran too, so let's assume it should be done by the end of next week?

**Comment by hroncok** [comment]
Fedora's pythran doesn't install at all on Fedora 32, so it cannot be broken any more than it already is. But I'll wait and update all 3 packages at once. Thanks.

**Comment by serge-sans-paille** [comment]
3.8 test suite passes on travis thanks to #27 , let's close this issue.
