### ISSUE TITLE
Version conflict with Jupyter-LSP?

### ISSUE THREAD

**Issue by marimeireles** [serge-sans-paille/gast#51]
When trying to interact with jupyter-lsp, I get the following on my devtools:

```
lsp-ws-connection initialization failure Error: pkg_resources.ContextualVersionConflict: (gast 0.4.0 (/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages), Requirement.parse('gast~=0.3.3'), {'beniget'})
    o index.js:10
    M index.js:10
    M index.js:10
    M index.js:10
    u setImmediate.js:16
    d setImmediate.js:31
    n setImmediate.js:87
index.js:10:526255
```

Or in my jupyter terminal:

```
2020-09-10 15:46:22,274 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 0
Traceback (most recent call last):
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pyls/python_ls.py", line 208, in m_initialize
    self.config = config.Config(rootUri, initializationOptions or {},
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pyls/config/config.py", line 53, in __init__
    entry_point.load()
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in load
    self.require(*args, **kwargs)
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2494, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (gast 0.4.0 (/home/mariana/miniconda3/envs/pyls-memestra/lib/python3.8/site-packages), Requirement.parse('gast~=0.3.3'), {'beniget'})

```

If you're interested in reproducing the steps are:
1. Create an environment that contains:
`conda install -c conda-forge memestra jupyter-lsp 'jupyterlab>=2,<2.1.0a0' 'nodejs>=13' python-language-server pyls-memestra`
2. `jupyter labextension install @krassowski/jupyterlab-lsp`
3. Clone `pyls-memestra` repo: `git@github.com:QuantStack/pyls-memestra.git`
4. Open `jupyter lab` and run the example

If you do the same thing but with `gast=0.3.3`, everything works perfectly.

Please let me know if I can be of any other assistance to you!

I thought it might be something with my python version?
Here is a [cc](https://pastebin.com/x1pJTsGH) of my `conda list`. Thanks!

**Comment by serge-sans-paille** [comment]
beniget hasn't been updated on conda, I've pinged the maintainer https://github.com/conda-forge/beniget-feedstock/pull/5

**Comment by serge-sans-paille** [comment]
That should be fine now, can you double-check?

**Comment by marimeireles** [comment]
Fixed, that was the exact issue. Thanks @serge-sans-paille
